apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: jenkins-ingress
  namespace: jenkins
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - jenkins.docker.internal
    secretName: nginxsecret
  rules:
  - host: jenkins.docker.internal
    http:
      paths:
      - backend:
          serviceName: jenkins
          servicePort: 8080
        path: /
status:
  loadBalancer: {}